
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4rWzOunJy7h
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Autoplay from "embla-carousel-autoplay"
import { CarouselItem, CarouselContent, Carousel } from "@/components/ui/carousel"
import { useRef } from "react";

export function CarouselSh() {


  return (
    (<section className="flex  w-full flex-col">
      <Carousel className="flex-1" 
        plugins={[
          Autoplay({
            delay: 20000,
          }),
        ]}
      >
        <CarouselContent >
          <CarouselItem>
            <div className="relative h-2/3 w-full h-full">
              <img
                alt="Hero Image 1"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1600/800",
                  objectFit: "cover",
                }}
                width="1600" />
              <div
                className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
              <div
                className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Unleash Your Creativity</h1>
                <p className="max-w-md text-lg md:text-xl">
                  Discover the ultimate platform to bring your ideas to life.
                </p>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-2/3 w-full">
              <img
                alt="Hero Image 2"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1600/800",
                  objectFit: "cover",
                }}
                width="1600" />
              <div
                className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
              <div
                className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Elevate Your Brand</h1>
                <p className="max-w-md text-lg md:text-xl">
                  Unlock the power of cutting-edge design tools and features.
                </p>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-2/3 w-full">
              <img
                alt="Hero Image 3"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1600/800",
                  objectFit: "cover",
                }}
                width="1600" />
              <div
                className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
              <div
                className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Ignite Your Vision</h1>
                <p className="max-w-md text-lg md:text-xl">
                  Transform your ideas into stunning, high-performing websites.
                </p>
              </div>
            </div>
          </CarouselItem>
        </CarouselContent>
      </Carousel>
    </section>)
  );
}
