/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4rWzOunJy7h
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Autoplay from "embla-carousel-autoplay"
import { CarouselItem, CarouselContent, Carousel } from "@/components/ui/carousel"
import { useRef } from "react"
const img1 =
    "https://images.unsplash.com/photo-1542690563-ca10289ac117?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
const img2 =
    "https://images.unsplash.com/photo-1442570468985-f63ed5de9086?q=80&w=2420&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
const img3 =
    "https://images.unsplash.com/photo-1426086800127-2601510ca027?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

export function CarouselSh() {
    return (
        <section className="flex w-full flex-col">
            <Carousel
                className="flex-1 select-none"
                plugins={[
                    Autoplay({
                        delay: 3000,
                    }),
                ]}
            >
                <CarouselContent className="max-h-[600px]">
                    <CarouselItem>
                        <div className="relative h-full w-full">
                            <img
                                alt="Hero Image 1"
                                className="h-full w-full object-cover brightness-50"
                                height="800"
                                src={img1}
                                style={{
                                    aspectRatio: "1600/800",
                                    objectFit: "cover",
                                }}
                                width="1600"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                            <div className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                                <h1 className="text-2xl font-bold tracking-tight sm:text-5xl md:text-6xl">
                                    RRE India: Driving Railway Excellence
                                </h1>
                                <p className="max-w-md md:text-xl">Trusted Locomotive Engine Part Suppliers</p>
                            </div>
                        </div>
                    </CarouselItem>
                    <CarouselItem>
                        <div className="relative h-full w-full">
                            <img
                                alt="Hero Image 2"
                                className="h-full w-full object-cover brightness-50"
                                height="800"
                                src={img2}
                                style={{
                                    aspectRatio: "1600/800",
                                    objectFit: "cover",
                                }}
                                width="1600"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                            <div className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                                <h1 className="text-2xl font-bold tracking-tight sm:text-5xl md:text-6xl">
                                    Powering the Railroad Industry
                                </h1>
                                <p className="max-w-md md:text-xl">Providing Quality Engine Parts for GE, EMD & ALCO</p>
                            </div>
                        </div>
                    </CarouselItem>
                    <CarouselItem>
                        <div className="relative h-full w-full">
                            <img
                                alt="Hero Image 3"
                                className="h-full w-full object-cover brightness-50"
                                height="800"
                                src={img3}
                                style={{
                                    aspectRatio: "1600/800",
                                    objectFit: "cover",
                                }}
                                width="1600"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                            <div className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
                                <h1 className="text-2xl font-bold tracking-tight sm:text-5xl md:text-6xl">
                                    Premium Locomotive Engine Parts
                                </h1>
                                <p className="max-w-md md:text-xl">
                                    Quality Locomotive Parts from India's Leading Supplier
                                </p>
                            </div>
                        </div>
                    </CarouselItem>
                </CarouselContent>
            </Carousel>
        </section>
    )
}
