"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jbJO4XUFXKb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import Link from "next/link"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import {
    NavigationMenuTrigger,
    NavigationMenuLink,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuList,
    NavigationMenu,
} from "@/components/ui/navigation-menu"
import { logoImg } from "./navbar"

export function NavLat() {
    return (
        <>
            <header className="fixed inset-0 top-5 z-10 mx-auto flex h-20 w-full max-w-[900px] shrink-0 items-center rounded-full bg-white px-4 shadow-lg md:px-6">
                <MobileNav />
                <nav className="hidden w-full lg:flex">
                    <DesktopNav />
                </nav>
            </header>
            <div className="mb-20 md:mb-16" />
        </>
    )
}

export const DesktopNav = () => {
    return (
        <div className="flex w-full justify-between">
            <div className="w-[150px]">
                <Link className="flex hidden items-center gap-2 text-lg font-semibold lg:flex" href="/">
                    <img className="h-12 w-auto" src={logoImg} alt="Your Company" />
                    <span className="sr-only">Acme Inc</span>
                </Link>
            </div>
            <NavigationMenu>
                <NavigationMenuList>
                    <NavigationMenuLink asChild>
                        <Link
                            className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                            href="/"
                        >
                            Home
                        </Link>
                    </NavigationMenuLink>
                    <NavigationMenuItem>
                        <NavigationMenuTrigger>
                            <Link className="flex w-full items-center py-2" href="/products">
                                Products
                            </Link>
                        </NavigationMenuTrigger>
                        <NavigationMenuContent>
                            <div className="grid w-[400px] p-2">
                                <NavigationMenuLink asChild>
                                    <Link
                                        className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-white p-4 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                                        href="/products/emd"
                                    >
                                        <div className="text-sm font-medium leading-none group-hover:underline">
                                            EMD
                                        </div>
                                        <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                            Learn more about our flagship product.
                                        </div>
                                    </Link>
                                </NavigationMenuLink>
                                <NavigationMenuLink asChild>
                                    <Link
                                        className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-white p-4 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                                        href="/products/alco"
                                    >
                                        <div className="text-sm font-medium leading-none group-hover:underline">
                                            ALCO
                                        </div>
                                        <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                            Explore our latest product offering.
                                        </div>
                                    </Link>
                                </NavigationMenuLink>
                                <NavigationMenuLink asChild>
                                    <Link
                                        className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-white p-4 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                                        href="/products/ge"
                                    >
                                        <div className="text-sm font-medium leading-none group-hover:underline">GE</div>
                                        <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                            Check out our enterprise-grade solution.
                                        </div>
                                    </Link>
                                </NavigationMenuLink>
                            </div>
                        </NavigationMenuContent>
                    </NavigationMenuItem>
                    <NavigationMenuLink asChild>
                        <Link
                            className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                            href="#"
                        >
                            Contact Us
                        </Link>
                    </NavigationMenuLink>
                    <NavigationMenuLink asChild>
                        <Link
                            className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                            href="#"
                        />
                    </NavigationMenuLink>
                </NavigationMenuList>
            </NavigationMenu>
        </div>
    )
}

export const MobileNav = () => {
    return (
        <Sheet>
            <SheetTrigger asChild>
                <Button className="lg:hidden" size="icon" variant="outline">
                    <MenuIcon className="h-6 w-6" />
                    <span className="sr-only">Toggle navigation menu</span>
                </Button>
            </SheetTrigger>
            <SheetContent side="left">
                <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
                    <MountainIcon className="h-6 w-6" />
                    <span className="sr-only">Acme Inc</span>
                </Link>
                <nav className="grid gap-2 py-6">
                    <Collapsible className="grid gap-4">
                        <CollapsibleTrigger className="flex w-full items-center text-lg font-semibold [&[data-state=open]>svg]:rotate-90">
                            Products
                            <ChevronRightIcon className="ml-auto h-5 w-5 transition-all" />
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                            <div className="-mx-6 grid gap-6 bg-gray-100 p-6 dark:bg-gray-800">
                                <Link className="group grid h-auto w-full justify-start gap-1" href="/products/emd">
                                    <div className="text-sm font-medium leading-none group-hover:underline">EMD</div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Learn more about our flagship product.
                                    </div>
                                </Link>
                                <Link className="group grid h-auto w-full justify-start gap-1" href="/products/alco">
                                    <div className="text-sm font-medium leading-none group-hover:underline">ALCO</div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Explore our latest product offering.
                                    </div>
                                </Link>
                                <Link className="group grid h-auto w-full justify-start gap-1" href="/products/ge">
                                    <div className="text-sm font-medium leading-none group-hover:underline"></div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Check out our enterprise-grade solution.
                                    </div>
                                </Link>
                            </div>
                        </CollapsibleContent>
                    </Collapsible>
                    <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                        Pricing
                    </Link>
                    <Collapsible className="grid gap-4">
                        <CollapsibleTrigger className="flex w-full items-center text-lg font-semibold [&[data-state=open]>svg]:rotate-90">
                            Resources
                            <ChevronRightIcon className="ml-auto h-5 w-5 transition-all" />
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                            <div className="-mx-6 grid gap-6 bg-gray-100 p-6 dark:bg-gray-800">
                                <Link className="group grid h-auto w-full justify-start gap-1" href="#">
                                    <div className="text-sm font-medium leading-none group-hover:underline">Blog</div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Read our latest blog posts.
                                    </div>
                                </Link>
                                <Link className="group grid h-auto w-full justify-start gap-1" href="#">
                                    <div className="text-sm font-medium leading-none group-hover:underline">
                                        Documentation
                                    </div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Learn how to use our products.
                                    </div>
                                </Link>
                                <Link className="group grid h-auto w-full justify-start gap-1" href="#">
                                    <div className="text-sm font-medium leading-none group-hover:underline">
                                        Help Center
                                    </div>
                                    <div className="line-clamp-2 text-sm leading-snug text-gray-500 dark:text-gray-400">
                                        Get help with our products.
                                    </div>
                                </Link>
                            </div>
                        </CollapsibleContent>
                    </Collapsible>
                    <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                        About
                    </Link>
                    <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                        Contact
                    </Link>
                </nav>
            </SheetContent>
        </Sheet>
    )
}

function ChevronRightIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m9 18 6-6-6-6" />
        </svg>
    )
}

function MenuIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="4" x2="20" y1="12" y2="12" />
            <line x1="4" x2="20" y1="6" y2="6" />
            <line x1="4" x2="20" y1="18" y2="18" />
        </svg>
    )
}

function MountainIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    )
}
