/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aFHxvQ1vHD5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SectionFocus() {
    return (
        <section className="w-full py-12 md:py-24 lg:py-32">
            <div className="container grid grid-cols-1 gap-6 px-4 md:grid-cols-2 md:px-6">
                <div className="space-y-4 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-950">
                    <div className="flex items-center">
                        <CheckIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                    </div>
                    <h3 className="text-xl font-bold">Customer Requirement</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                        How well the product or service meets the customer's needs and specifications.
                    </p>
                </div>
                <div className="space-y-4 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-950">
                    <div className="flex items-center">
                        <StarIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                    </div>
                    <h3 className="text-xl font-bold">Product Quality</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                        The overall excellence, durability, and reliability of the product.
                    </p>
                </div>
                <div className="space-y-4 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-950">
                    <div className="flex items-center">
                        <ClockIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                    </div>
                    <h3 className="text-xl font-bold">On Time Delivery</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                        How consistently the product or service is delivered within the agreed upon timeframe.
                    </p>
                </div>
                <div className="space-y-4 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-950">
                    <div className="flex items-center">
                        <ThumbsUpIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                    </div>
                    <h3 className="text-xl font-bold">Customer Satisfaction</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                        The level of contentment and positive sentiment from the customer after using the product or
                        service.
                    </p>
                </div>
            </div>
        </section>
    )
}

export function CheckIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M20 6 9 17l-5-5" />
        </svg>
    )
}

export function ClockIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10" />
            <polyline points="12 6 12 12 16 14" />
        </svg>
    )
}

export function StarIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
    )
}

export function ThumbsUpIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M7 10v12" />
            <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
        </svg>
    )
}
